Fix failures related to NoMethodError: undefined method `clean'.
We were initializing the ExceptionWrapper incorrectly since it changed in Rails 5.

See the Rails Issue and related fix in another gem:

- https://github.com/rails/rails/issues/22846
- https://github.com/dejan/rails_panel/commit/3bdbfc9004d1f5f1e520d54f296c68fb6a70b040